service: laravel-with-basic

# オーソライザーが動作するruntime: nodejs10.x
# laravel(PHP)を動作するruntime: provided.al2
# 動作するruntimeが異なるのでここで指定しない(functionsの中で定義)
provider:
  name: aws
  # runtime: nodejs10.x
  region: ap-northeast-1
  stg: ${opt:stage, self:custom.defaultStage}

plugins:
  - ./vendor/bref/bref
  - serverless-plugin-ifelse
  - serverless-domain-manager

package:
  exclude:
    - node_modules/**
    - public/storage
    - storage/**
    - tests/**

# 変数定義
custom:
  # カスタムドメインの設定
  customDomain:
    domainName: laravel-demo.tk
    certificateName: 'laravel-demo.tk'
    # domainName: '${self:provider.stg}.koshikawa.net'
    # certificateName: '*.koshikawa.net'
    basePath: ''
    stage: ${self:provider.stg}
    createRoute53Record: true
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: false

  defaultStage: dev

  definitions:
    authorizer:
      # Lambda関数名（basic認証しない時はauthorizer以外を指定し、同じ名前のファンクションを用意する）
      name: ${file(./development.yml):app_dev}
      # name: authorizer
      # キャッシュ時間
      resultTtlInSeconds: 0
      # Lambda関数に渡すヘッダー名
      identitySource: method.request.header.Authorization
      # Lambdaイベントペイロード
      type: request

  
      
functions:
  website:
    runtime: provided.al2
    handler: public/index.php
    timeout: 28
    layers:
      - ${bref:layer.php-73-fpm}
    events: # アクセス時に呼ばれるファンクション
      - http:
          path: '/'
          method: any
          # TODO:ここでオーソライザーが走ってしまうので、この設定の有無を切り替えられるのがベスト
          authorizer: ${self:custom.definitions.authorizer}

  # basic認証時に走る
  authorizer:
    runtime: nodejs10.x
    handler: authorizer.handler

  # basci認証させたくないときに走らせる
  non_authorizer:
    runtime: nodejs10.x
    handler: non_authorizer.handler

# [AWSリソースの設定]APIGateWayにオーソライザーを設定
# オーソライザが401を返したときに「WWW-Authenticate」ヘッダを返却させるための設定
resources:
  Resources:
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.WWW-Authenticate: "'Basic'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'