service: lambda-authorizer-serverless

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1
  stg: ${opt:stage}

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: '/'
          method: any
      - http:
          path: '{proxy+}'
          method: any
